spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/solicitudes_transporte_db
    username: postgres
    password: 12345 #Recuerden cambiar la contraseña propia de uds para que les funcione la BBDD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    enabled: true
    path: /mgss/api-docs
  swagger-ui:
    enabled: true
    path: /mgss/swagger-ui.html
    try-it-out-enabled: true
    operations-sorter: method
  #paths-to-match: /api/v1/solicitud-servicios/**, /api/v1/solicitudes-paquetes/**

# AUTHENTICATION & AUTHORIZATION
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      access-token:
        expiration: 86400000 # a day
      id-token:
        expiration: 604800000 # 7 days